Repository Web-Ex-Machina/contao-smartgear, pull requests merged in 2022-11, with the labels that each got.

#226 Fix 2022 10 28
  docs/INSERT_TAGS.md
  src/Backend/Component/Blog/ConfigurationStep/General.php
  src/Backend/Component/Blog/EventListener/LoadDataContainerListener.php
  src/Backend/Component/Blog/ResetStep/General.php
  src/Backend/Component/Core/ConfigurationStep/General.php
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Core/EventListener/CompileFormFieldsListener.php
  src/Backend/Component/Core/EventListener/LoadDataContainerListener.php
  src/Backend/Component/Core/ResetStep/General.php
  src/Backend/Component/Events/ConfigurationStep/General.php
  src/Backend/Component/Events/EventListener/LoadDataContainerListener.php
  src/Backend/Component/Events/ResetStep/General.php
  src/Backend/Component/Faq/ConfigurationStep/General.php
  src/Backend/Component/Faq/EventListener/LoadDataContainerListener.php
  src/Backend/Component/Faq/ResetStep/General.php
  src/Backend/Component/FormContact/ConfigurationStep/General.php
  src/Backend/Component/FormContact/EventListener/ReplaceInsertTagsListener.php
  src/Backend/Component/FormContact/ResetStep/General.php
  src/Backend/Module/Extranet/ConfigurationStep/General.php
  src/Backend/Module/Extranet/ResetStep/General.php
  src/Backend/Module/FormDataManager/ConfigurationStep/General.php
  src/Backend/Module/FormDataManager/ConfigurationStepManager.php
  src/Backend/Module/FormDataManager/EventListener/CompileFormFieldsListener.php
  src/Backend/Module/FormDataManager/EventListener/ProcessFormDataListener.php
  src/Backend/Module/FormDataManager/ResetStep/General.php
  src/Backend/Module/FormDataManager/Resetter.php
  src/Classes/Backend/AbstractStep.php
  src/Classes/Backend/Block.php
  src/Classes/Backend/Traits/MessagesTrait.php
  src/Classes/Dca/Manipulator.php
  src/Classes/StringUtil.php
  src/Classes/UserGroupModelUtil.php
  src/Classes/Util.php
  src/Config/Component/Core/Core.php
  src/Config/Component/FormContact/FormContact.php
  src/DataContainer/Content.php
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Model/Module.php
  src/Override/ModuleBreadcrumb.php
  src/Resources/config/components.yml
  src/Resources/config/listeners.yml
  src/Resources/contao/config/config.php
  src/Resources/contao/dca/tl_content.php
  src/Resources/contao/dca/tl_sm_form_storage.php
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/public/contao_files/templates/smartgear/mod_newslist_nofilters.html5
  src/Resources/public/contao_files/templates/smartgear/settings/fr/form_warning_message.html5
  src/Resources/public/examples/balises_supplementaires_1.js
  src/Resources/public/examples/code_javascript_personnalise_1.js
  src/Resources/public/examples/formDataManager/fr/warning_message.html
Labels: bug, enhancement

#228 Feat : page sorting calculation
  src/Backend/Component/Blog/ConfigurationStep/General.php
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Events/ConfigurationStep/General.php
  src/Backend/Component/Faq/ConfigurationStep/General.php
  src/Backend/Component/FormContact/ConfigurationStep/General.php
  src/Backend/Module/Extranet/ConfigurationStep/General.php
  src/Classes/Util.php
Labels: bug, enhancement

#230 Fix : Form can have themselves as parent ...
  src/Backend/Component/Core/EventListener/CompileFormFieldsListener.php
  src/Backend/Module/FormDataManager/EventListener/CompileFormFieldsListener.php
  src/Backend/Module/FormDataManager/EventListener/ProcessFormDataListener.php
  src/Classes/FormUtil.php
  src/Resources/public/js/module/formdatamanager/frontend.js
Labels: bug

#231 [rsce_modal][translation] add proper translations to modal rsce
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_modal_config.php
Labels: Translations

#232 [rsce_quote][translation] add proper translation to backend config. r…
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_quote_config.php
Labels: Translations

#235 Fix : module footer
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Core/EventListener/ReplaceInsertTagsListener.php
  src/Config/Component/Core/Core.php
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/public/examples/footer_1.html
Labels: bug

#236 Fixes 2022-11-29
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Resources/contao/languages/fr/default.xlf
Labels: bug

#237 Fix 2022 11 29 2
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Migrations/V1_0_0/M202203231730/Migration.php
Labels: bug, enhancement
