Repository Web-Ex-Machina/contao-smartgear, pull requests merged in 2022-07, with the labels that each got.

#127 Issue 122 module extranet
  composer.json
  composer.lock
  docker/contao/4.13/contao-init.php
  docker/docker-compose-dev.yml
  docs/INSERT_TAGS.md
  src/Backend/Component/Core/ConfigurationStep/General.php
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Core/EventListener/CreateNewUserListener.php
  src/Backend/Module/Extranet/Block.php
  src/Backend/Module/Extranet/ConfigurationStep/General.php
  src/Backend/Module/Extranet/ConfigurationStepManager.php
  src/Backend/Module/Extranet/Dashboard.php
  src/Backend/Module/Extranet/EventListener/LoadDataContainerListener.php
  src/Backend/Module/Extranet/EventListener/ReplaceInsertTagsListener.php
  src/Backend/Module/Extranet/ResetStep/General.php
  src/Backend/Module/Extranet/ResetStepManager.php
  src/Backend/Smartgear.php
  src/Classes/Dca/Driver/DC_Table.php
  src/Classes/Dca/Field/Callback/Load.php
  src/Classes/Dca/Field/Callback/Save.php
  src/Classes/UserGroupModelUtil.php
  src/Classes/Util.php
  src/Config/Component/Core/Core.php
  src/Config/Module/Extranet/Extranet.php
  src/ContaoManager/Plugin.php
  src/DataContainer/Article.php
  src/DataContainer/Content.php
  src/DataContainer/Files.php
  src/DataContainer/Member.php
  src/DataContainer/MemberGroup.php
  src/DataContainer/Module.php
  src/DataContainer/NotificationLanguage.php
  src/DataContainer/NotificationMessage.php
  src/DataContainer/NotificationNotification.php
  src/DataContainer/Page.php
  src/DependencyInjection/WEMSmartgearExtension.php
  src/EventListener/CreateNewUserListener.php
  src/EventListener/LoadDataContainerListener.php
  src/EventListener/PersonalDataManager/UiListener.php
  src/Model/Member.php
  src/Resources/config/components.yml
  src/Resources/config/listeners.yml
  src/Resources/config/modules.yml
  src/Resources/config/services.yml
  src/Resources/contao/config/config.php
  src/Resources/contao/dca/tl_member.php
  src/Resources/contao/languages/en/default.xlf
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/contao/languages/fr/modules.xlf
  src/Resources/contao/templates/backend/be_wem_sg_install_step_field.html5
  src/Resources/contao/templates/backend/module/extranet/be_wem_sg_block_extranet_dashboard.html5
  src/Resources/contao/templates/backend/module/extranet/be_wem_sg_install_block_reset_step_extranet_general.html5
  src/Resources/public/examples/extranet/fr/change_data.html
  src/Resources/public/examples/extranet/fr/password.html
  src/Resources/public/examples/extranet/fr/subscription.html
  src/Resources/public/examples/formContact/fr/admin_form.html
  src/Resources/public/examples/formContact/fr/user_form.html
Labels: enhancement

#163 Rsce rework and improvment / notations
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_notations.html5
  src/Resources/public/contao_files/templates/rsce/rsce_ratings.html5
  src/Resources/public/contao_files/templates/rsce/rsce_ratings_config.php
Labels: enhancement

#165 Issue 160 check usergroup configuration
  src/Backend/Component/Blog/ConfigurationStep/General.php
  src/Backend/Component/Blog/ResetStep/General.php
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Events/ConfigurationStep/General.php
  src/Backend/Component/Events/ResetStep/General.php
  src/Backend/Component/Faq/ConfigurationStep/General.php
  src/Backend/Component/Faq/ResetStep/General.php
  src/Backend/Component/FormContact/ConfigurationStep/General.php
  src/Backend/Component/FormContact/ResetStep/General.php
  src/Backend/Module/Extranet/ConfigurationStep/General.php
  src/Backend/Module/Extranet/ResetStep/General.php
  src/Classes/Config/ConfigModuleInterface.php
  src/Classes/UserGroupModelUtil.php
  src/Config/Component/Blog/Blog.php
  src/Config/Component/Core/Core.php
  src/Config/Component/Events/Events.php
  src/Config/Component/Faq/Faq.php
  src/Config/Component/FormContact/FormContact.php
  src/Config/Module/Extranet/Extranet.php
  src/DataContainer/Article.php
  src/DataContainer/Content.php
  src/DataContainer/Files.php
  src/DataContainer/Member.php
  src/DataContainer/MemberGroup.php
  src/DataContainer/Module.php
  src/DataContainer/Page.php
  src/DataContainer/User.php
  src/DataContainer/UserGroup.php
  src/Model/Module.php
Labels: bug, enhancement

#130 issue #126 : adding StyleManager optgroup for colors
  composer.json
  docker/contao/4.13/contao-init.php
  src/Config/Manager/FramwayCombined.php
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Widget/ComponentStyleSelect.php
Labels: enhancement

#167 Issue 166 rsce rework and improvment / pd fviewer
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_pdfViewer.html5
  src/Resources/public/contao_files/templates/rsce/rsce_pdfViewer_config.php
Labels: enhancement

#168 Rsce rework and improvment / priceCards
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_priceCards.html5
  src/Resources/public/contao_files/templates/rsce/rsce_priceCards_config.php
Labels: enhancement

#172 Issue 170 sort rsce in proper categories
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_blockCard_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_counter_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_heroStart_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_heroStop_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_hero_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_listIcons_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_modal_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_pdfViewer_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_priceCards_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_ratings_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_tabs_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_testimonials_config.php
  src/Resources/public/contao_files/templates/rsce/rsce_timeline_config.php
Labels: enhancement

#175 Fix : content element availability
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Resources/contao/dca/tl_content.php
Labels: bug

#176 Fix : template priority
  src/Hooks/ParseTemplateHook.php
Labels: bug

#177 Fix : Style Manager working on native Contao Element
  src/Resources/contao/dca/tl_content.php
Labels: bug

#180 Fix ce_hyperlink template markup
  src/Resources/public/contao_files/templates/smartgear/ce_hyperlink.html5
Labels: bug

#181 Issue 178 rsce modal use buttons instead of a
  src/Resources/public/contao_files/templates/rsce/rsce_modal.html5
  src/Resources/public/contao_files/templates/smartgear/ce_hyperlink.html5
Labels: invalid
