Repository Web-Ex-Machina/contao-smartgear, pull requests merged in 2022-06, with the labels that each got.

#120 Feat : adding missing framway vendor CSS stylesheet
  src/Resources/public/examples/balises_supplementaires_1.js
Labels: enhancement

#123 Fix : unit tests
  src/Config/Component/Core/Core.php
  tests/unit/Classes/Config/ManagerCoreTest.php
  tests/unit/Config/CoreTest.php
  tests/unit/Migrations/MigrationTest.php
Labels: bug

#121 Fix : tl_layout.framework should be empty when created during Smartgear installation
  src/Backend/Component/Core/ConfigurationStep/Website.php
Labels: bug

#125 issue #124 : error when adding a distant theme
  src/Backend/Component/Core/ConfigurationStep/FramwayConfiguration.php
  src/Classes/UtilFramway.php
  src/Config/Framway.php
  src/Config/Manager/Framway.php
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/contao/templates/backend/component/core/be_wem_sg_install_block_configuration_step_core_framway_configuration.html5
Labels: bug

#131 Fix : little issues
  docker/docker-compose-dev.yml
  src/Resources/contao/templates/backend/component/core/be_wem_sg_install_block_configuration_step_core_website.html5
Labels: enhancement

#135 Rework and improve rsce Counter
  src/Resources/public/contao_files/templates/rsce/rsce_counter_config.php
Labels: enhancement

#147 RSCE rework and improvment / hero start - stop
  src/Resources/public/contao_files/templates/rsce/rsce_heroStart.html5
  src/Resources/public/contao_files/templates/rsce/rsce_heroStart_config.php
Labels: enhancement

#137 Issue 136 remove rsce foldingbox
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_foldingbox.html5
  src/Resources/public/contao_files/templates/rsce/rsce_foldingbox_config.php
Labels: invalid

#148 RSCE rework and improvment / tabs
  src/Resources/public/contao_files/templates/rsce/rsce_tabs_config.php
Labels: enhancement

#151 Fix : templates and assets install
  src/Backend/Component/Core/ConfigurationStep/FramwayRetrievalMinimal.php
  src/Resources/config/components.yml
Labels: bug

#149 RSCE rework and improvment / Quote
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Resources/public/contao_files/templates/rsce/rsce_quote.html5
  src/Resources/public/contao_files/templates/rsce/rsce_quote_config.php
Labels: enhancement

#157 update some translations so they are on tl_content level and can be u…
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_blockCard_config.php
Labels: enhancement

#158 Fix : Smartgear loaded after terminal42/notification_center
  src/ContaoManager/Plugin.php
Labels: bug

#159 Fix : webmaster can access client files
  src/Backend/Component/Core/ConfigurationStep/Website.php
Labels: bug

#162 Issue 161 fix various issue on block card
  src/Resources/public/contao_files/templates/rsce/rsce_blockCard.html5
  src/Resources/public/contao_files/templates/rsce/rsce_blockCard_config.php
Labels: bug
