Repository Web-Ex-Machina/contao-smartgear, pull requests merged in 2023-07, with the labels that each got.

#268 Fix fdm get referer page id return type
  .gitignore
  CHANGELOG.md
  composer.lock
  src/Backend/Module/FormDataManager/EventListener/ProcessFormDataListener.php
  src/Migrations/V1_0_14/M202307061615/Migration.php
  src/Resources/config/migrations.yml
  src/Resources/config/services.yml
  src/Resources/contao/dca/tl_sm_form_storage.php
  src/Resources/contao/languages/fr/default.xlf
Labels: bug

#273 Feat : missing translation key + placeholder migration
  CHANGELOG.md
  src/Migrations/PlaceholderMigration.php
  src/Resources/config/migrations.yml
  src/Resources/config/services.yml
  src/Resources/contao/languages/en/tl_content.xlf
  src/Resources/contao/languages/fr/default.xlf
Labels: bug, enhancement

#272 Feat: add rsce quoteWrating
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_quoteWrating.html5
  src/Resources/public/contao_files/templates/rsce/rsce_quoteWrating_config.php
Labels: enhancement

#270 Feat: improve rsce counter
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/public/contao_files/templates/rsce/rsce_counter.html5
  src/Resources/public/contao_files/templates/rsce/rsce_counter_config.php
Labels: enhancement

#276 Feat : Airtable API with 2 keys
  CHANGELOG.md
  src/Api/Airtable/V0/Api.php
  src/Backend/Component/Core/ConfigurationStep/General.php
  src/Config/Component/Core/Core.php
  src/Resources/config/migrations.yml
  src/Resources/config/services.yml
  src/Resources/contao/languages/fr/default.xlf
Labels: enhancement

#278 Feat : adding 'scroll' value to header sticky
  src/Resources/contao/dca/tl_module.php
  src/Resources/contao/languages/fr/explain.xlf
  src/Resources/contao/languages/fr/tl_content.xlf
  src/Resources/contao/templates/components/mod_wem_sg_header.html5
  src/Resources/public/contao_files/assets/framway/build/combined/framway.scss
  src/Resources/public/contao_files/assets/framway/build/css/framway.css
  src/Resources/public/contao_files/assets/framway/build/js/framway.js
  src/Resources/public/contao_files/assets/framway/framway.config.js
Labels: enhancement

#279 Fix 267
  CHANGELOG.md
  docker/build.sh
  src/Backend/Component/Blog/ConfigurationStep/General.php
  src/Backend/Component/Core/ConfigurationStep/Website.php
  src/Backend/Component/Core/Dashboard.php
  src/Backend/Component/Events/ConfigurationStep/General.php
  src/Backend/Component/Faq/ConfigurationStep/General.php
  src/Backend/Component/FormContact/ConfigurationStep/General.php
  src/Backend/Module/Extranet/ConfigurationStep/General.php
  src/Backend/Smartgear.php
  src/Classes/Analyzer/Htaccess.php
  src/Classes/Backend/Block.php
  src/Classes/Backend/Traits/ActionsTrait.php
  src/Classes/Config/Manager/ManagerEnvInterface.php
  src/Classes/Config/Manager/ManagerInterface.php
  src/Classes/Config/Manager/ManagerJson.php
  src/Classes/Config/Manager/ManagerJsonInterface.php
  src/Classes/Config/Manager/ManagerYamlInterface.php
  src/Classes/Migration/MigrationAbstract.php
  src/Config/Manager/EnvFile.php
  src/DataContainer/NotificationGateway.php
  src/DataContainer/NotificationLanguage.php
  src/DataContainer/NotificationMessage.php
  src/DataContainer/NotificationNotification.php
  src/EventListener/GeneratePageListener.php
  src/Migrations/PlaceholderMigration.php
  src/Migrations/V1_0_0/M202203231730/Migration.php
  src/Migrations/V1_0_0/M202205130814/Migration.php
  src/Migrations/V1_0_0/MigrationAbstract.php
  src/Migrations/V1_0_1/M202301050800/Migration.php
  src/Migrations/V1_0_10/M202305311835/Migration.php
  src/Migrations/V1_0_11/M202306152248/Migration.php
  src/Migrations/V1_0_12/M202306231015/Migration.php
  src/Migrations/V1_0_13/M202306271601/Migration.php
  src/Migrations/V1_0_14/M202307061615/Migration.php
  src/Migrations/V1_0_2/M202301051700/Migration.php
  src/Migrations/V1_0_3/M202301100950/Migration.php
  src/Migrations/V1_0_4/M202301110935/Migration.php
  src/Migrations/V1_0_5/M202301131435/Migration.php
  src/Migrations/V1_0_7/M202303291542/Migration.php
  src/Migrations/V1_0_8/M202303291542/Migration.php
  src/Migrations/V1_0_9/M202305012112/Migration.php
  src/Resources/config/migrations.yml
  src/Resources/config/services.yml
  src/Resources/contao/dca/tl_sm_form_storage_data.php
  src/Resources/contao/languages/fr/default.xlf
  src/Resources/contao/languages/fr/explain.xlf
  src/Resources/contao/languages/fr/modules.xlf
  src/Resources/contao/languages/fr/tl_user_group.xlf
  src/Resources/contao/templates/backend/be_wem_sg_install.html5
  src/Resources/contao/templates/backend/be_wem_sg_install_steps.html5
  src/Resources/contao/templates/backend/configurationmanager/be_wem_sg_configurationmanager.html5
  src/Resources/contao/templates/backend/configurationmanager/be_wem_sg_configurationmanager_checkbox.html5
  src/Resources/contao/templates/backend/configurationmanager/be_wem_sg_configurationmanager_input.html5
  src/Resources/contao/templates/backend/configurationmanager/be_wem_sg_configurationmanager_select.html5
  src/Resources/contao/templates/backend/configurationmanager/be_wem_sg_configurationmanager_textarea.html5
  src/Resources/contao/templates/components/mod_wem_sg_header.html5
Labels: bug, enhancement
